version: '2'
services:
  cabin_db:
    image: mysql:latest
    volumes:
      - my-db:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: db_ffx11
      MYSQL_USER: springuser
      MYSQL_PASSWORD: springuspw
      MYSQL_ROOT_PASSWORD: admin

volumes:
  my-db: